/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package html.dls.with.kotlin

fun main() {
    with(HtmlDsl) { // this: HTMLDSL
        /*val result =
            html {  // this: HTML
            }.render()
        println(result)*/
    }
}
